Feature/app backbone
zilton7/weather-app pull request #1
Opened 2021-05-12 18:07 UTC by zilton7

2021-05-12 18:59 UTC, NtwaliHeritier reviewed
### **STATUS: INVALID❌❌❌❌**

Hello @zilton7 
Great work on this project, however, I invalidated this PR because of the following reasons.
- It doesn't have a package.json and webpack configurations hence unable to use it.
- The readme file doesn't correspond to the project. For example: there is no src/index.js file.

Kindly make appropriate changes and ask for another review👍👌

Happy coding💻💻💻

2021-05-12 20:32 UTC, teekaytech requested changes
### Status: Invalid Code Review Request :x: 

__Hi team, I commend you for the great effort put into this project. However, I have to mark the project as invalid due to the following reasons:__

- [ ] You did not work with Git Flow
- The `main` or `master` branch is completely missing.
- With GitFlow, you're expected to have at least three(3) branches: production <code>master</code> or `main` branch + the development <code>develop</code> branch + Pull Requests from feature branches to the <code>develop</code> (<a href="https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/git_flow_requirement.png">screenshot</a> from Pathwright)

This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!


* * *
**Please, do not open a new Pull Request for subsequent reviews. You should use the same Pull Request submitted for the first review (either valid or invalid) unless it is requested otherwise.**

**Always post your inquiries and questions on this PR thread as a comment. You can mention me (@teekaytech) so I can see your comments and respond.**

* * * 

**_You can reach out to me on Twitter (@ola_lere), Github(@teekaytech), or slack (@taofeekolalere )_**

Happy Coding :man_technologist:

2021-05-12 20:46 UTC, zilton7 commented
Added main branch

2021-05-12 22:53 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Zil Norvilis** 
Good job with your first for this project :muscle:  :muscle:
The page is properly working as expected :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] Your page should change its appearance based on the received data
- [ ] You should use async-await for the API call
- [ ] In your README file, you should include the command to run your project
- [ ] Keep the application logic separated from DOM manipulation tasks 
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-05-13 06:46 UTC, zilton7 commented
>     * [x]  Your page should change its appearance based on the received data

it does that, the Text that shows temperature changes color according to   temperature

2021-05-13 07:37 UTC, whiz25 requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work making the required changes.
Let's make some more changes before merging.
- [x] Your app does not display the weather results. Nothing happens after hitting ENTER. Try to fix that
![Screenshot from 2021-05-13 10-28-04](https://user-images.githubusercontent.com/19773024/118094124-ffbece00-b3d6-11eb-869c-fc7a15975662.png)
- [x] Separate DOM and logic from `functions.js` file. Check my comment

### Martin Afani
#### Slack: whiz25

2021-05-13 07:37 UTC, whiz25 commented on src/functions.js
> +    const unitSelection = document.querySelector('input[name="unit"]:checked')
- Put this code in the dom-manipulations file. Only pure js logic should live here.

2021-05-13 08:11 UTC, descholar-ceo approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @zilton7  , your project is approved :tada: :tada: :tada: 
You have implemented all requested changes && requirements for this project to mark it as complete, it doesn't need more changes, you can go ahead and merge all of the changes on base branch,

Don't forget to fill the mandatory project completion form, and see you to next project,

Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2021-05-13 08:15 UTC, merged